### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by cgore**

### CODE REVIEW

**Comment by glenjamin** [comment]
Seems fairly sensible, could you make the following small changes please?

* remove :dev profile now that 1.7 is default
* remove ancient - imo this belongs in the user profile unless CI is going to run it
* put ring-core in :test and only override in :1.4

Cheers 🎉

**Comment by cgore** [comment]
Sure, that sounds good.

**Comment by cgore** [comment]
I'm confused as to how to make substitution for ring-core work.  I would have assumed the following, but it's giving me weird errors:

```clojure
  :profiles {:test {:dependencies [[net.cgrand/moustache "1.1.0"
                                    :exclusions
                                    [[org.clojure/clojure]
                                     [ring/ring-core]]]
                                   [javax.servlet/servlet-api "2.5"]
                                   [hiccup "1.0.5"]
                                   [ring/ring-core "1.4.0"]]
                    :resource-paths ["test-resources"]}
             :1.4  {:dependencies [^:replace [org.clojure/clojure "1.4.0"]
                                   ^:replace [ring/ring-core "1.3.2"]]}
             :1.5  {:dependencies [^:replace [org.clojure/clojure "1.5.1"]]}
             :1.6  {:dependencies [^:replace [org.clojure/clojure "1.6.0"]]}}
```

Do you know how to make this work?

**Comment by glenjamin** [comment]
That looks like it should work to me. I can live without that exact config as long as `lein test` with standard profiles works

**Comment by glenjamin** [comment]
In my testing I couldn't get 1.4 to work, so decided to drop support instead.

**Pull request merged**
